//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_ComputerRoom
    {
        public int ID { get; set; }
        public string Dept_Id { get; set; }
        public Nullable<int> jg { get; set; }
        public Nullable<int> kt { get; set; }
        public Nullable<int> sxt { get; set; }
        public Nullable<int> mhq { get; set; }
        public Nullable<int> UPS { get; set; }
        public Nullable<int> fhm { get; set; }
        public Nullable<int> fhdb { get; set; }
        public Nullable<int> qtmhzz { get; set; }
        public Nullable<int> fljsb { get; set; }
        public Nullable<int> fjdsb { get; set; }
        public Nullable<int> fdcgr { get; set; }
        public Nullable<int> fcsb { get; set; }
        public Nullable<int> fwq { get; set; }
        public System.DateTime OperatTime { get; set; }
        public int OperatPid { get; set; }
    }
}
