//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_ComputerRoom_1
    {
        public int ID { get; set; }
        public string Dept_Name { get; set; }
        public string jfwlwz { get; set; }
        public int mj { get; set; }
        public string jflx { get; set; }
        public string lsgx { get; set; }
        public string sfjrczww { get; set; }
        public string jfglyxm { get; set; }
        public string lxfs { get; set; }
        public System.DateTime OperatTime { get; set; }
        public int OperatPid { get; set; }
    }
}
