//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_GenuineSoftware_1
    {
        public int ID { get; set; }
        public string Dept_Name { get; set; }
        public Nullable<int> tsj { get; set; }
        public Nullable<int> bjb { get; set; }
        public Nullable<int> bjrqzwww { get; set; }
        public Nullable<int> jrzwwwsl { get; set; }
        public Nullable<int> az260tqsl { get; set; }
        public string sfdbd { get; set; }
        public string czxtlx { get; set; }
        public string yzczxt { get; set; }
        public Nullable<int> yysqs1 { get; set; }
        public string bgrjlx { get; set; }
        public string sftytg1 { get; set; }
        public Nullable<int> yysqs { get; set; }
        public string sftytg { get; set; }
        public Nullable<int> tgsl { get; set; }
        public System.DateTime OperatTime { get; set; }
        public int OperatPid { get; set; }
    }
}
