//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_Network_1
    {
        public int ID { get; set; }
        public string Dept_Name { get; set; }
        public string bgdd { get; set; }
        public string lxdh { get; set; }
        public Nullable<int> jrzwwwzdsl { get; set; }
        public Nullable<int> jrgwwzdsl { get; set; }
        public string jrzwwwIPdzd { get; set; }
        public Nullable<int> scjhj { get; set; }
        public Nullable<int> ecjhj { get; set; }
        public Nullable<int> lyq { get; set; }
        public Nullable<int> llfzjh { get; set; }
        public Nullable<int> gx { get; set; }
        public Nullable<int> wxjrd { get; set; }
        public Nullable<int> wxzj { get; set; }
        public string flwck { get; set; }
        public System.DateTime OperatTime { get; set; }
        public int OperatPid { get; set; }
        public Nullable<int> gdj { get; set; }
    }
}
