//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_ResourceCatalog
    {
        public int ID { get; set; }
        public string Dept_Id { get; set; }
        public Nullable<int> zymlsl { get; set; }
        public Nullable<int> ysjzyl { get; set; }
        public Nullable<int> dysjxl { get; set; }
        public Nullable<int> gxcs { get; set; }
        public Nullable<int> fwl { get; set; }
        public System.DateTime OperatTime { get; set; }
        public int OperatPid { get; set; }
    }
}
