//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_Security
    {
        public int ID { get; set; }
        public string Dept_Id { get; set; }
        public string bswz { get; set; }
        public Nullable<int> fhq { get; set; }
        public Nullable<int> rqjc { get; set; }
        public Nullable<int> VPNsb { get; set; }
        public string VPNsbxh { get; set; }
        public string VPNsbpp { get; set; }
        public Nullable<int> zmaqfhsb { get; set; }
        public string zmaqfhsbxh { get; set; }
        public string zmaqfhsbpp { get; set; }
        public Nullable<int> mmj { get; set; }
        public Nullable<int> jsmb { get; set; }
        public Nullable<int> yjsjsb { get; set; }
        public string yjsjsbxh { get; set; }
        public string yjsjsbpp { get; set; }
        public string sfrzwg { get; set; }
        public Nullable<int> yyfzjh { get; set; }
        public Nullable<int> xhgrq { get; set; }
        public Nullable<int> swxwgl { get; set; }
        public Nullable<int> wljk { get; set; }
        public Nullable<int> fwqjkpt { get; set; }
        public Nullable<int> ywglpt { get; set; }
        public Nullable<int> wyfcg { get; set; }
        public Nullable<int> zdjkASM { get; set; }
        public System.DateTime OperatTime { get; set; }
        public int OperatPid { get; set; }
    }
}
