//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_Service_2
    {
        public int ID { get; set; }
        public string IPdz { get; set; }
        public System.DateTime tjsj { get; set; }
        public string xnjm { get; set; }
        public string Dept_Name { get; set; }
        public string xtmc { get; set; }
        public string bz { get; set; }
        public string CPU { get; set; }
        public string nc { get; set; }
        public string ypkj { get; set; }
        public string czxt { get; set; }
        public string glyhm { get; set; }
        public string glmm { get; set; }
        public string whyhm1 { get; set; }
        public string whmm1 { get; set; }
        public string sjyhm { get; set; }
        public string sjmm { get; set; }
    }
}
