//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_Security_xxsl_1
    {
        public int ID { get; set; }
        public string Dept_Name { get; set; }
        public string aqsbhrjmc { get; set; }
        public string sfbs { get; set; }
        public int sl { get; set; }
        public string pp { get; set; }
        public string xh { get; set; }
        public System.DateTime gmrq { get; set; }
        public int gmjq { get; set; }
    }
}
