//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_Service_1
    {
        public int ID { get; set; }
        public string Dept_Name { get; set; }
        public string fwqbh { get; set; }
        public string xh { get; set; }
        public System.DateTime gmrq { get; set; }
        public System.DateTime gbrq { get; set; }
        public string cpbb { get; set; }
        public string xlh { get; set; }
        public string gdzcbh { get; set; }
        public string wlwz { get; set; }
        public string jgwz { get; set; }
        public string IPdz { get; set; }
        public string ym { get; set; }
        public string wg { get; set; }
        public string jqm { get; set; }
        public string zyywyy { get; set; }
        public string czxt { get; set; }
        public string sjkxt { get; set; }
        public string CPU { get; set; }
        public string nc { get; set; }
        public string yp { get; set; }
        public string ywsj { get; set; }
        public string sfrb { get; set; }
        public string zycd { get; set; }
        public string glyhm { get; set; }
        public string glmm { get; set; }
        public string yhm1 { get; set; }
        public string mm1 { get; set; }
        public string xlhbbgl { get; set; }
        public string sfjh { get; set; }
        public string jhm { get; set; }
        public int sykyxjhsl { get; set; }
        public string sfzb { get; set; }
        public System.DateTime OperatTime { get; set; }
        public int OperatPid { get; set; }
    }
}
