//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_User
    {
        public int user_Id { get; set; }
        public string user_Name { get; set; }
        public string user_Pwd { get; set; }
        public string user_TrueName { get; set; }
        public Nullable<int> user_Purview { get; set; }
        public string user_Dept { get; set; }
        public Nullable<int> user_Sign { get; set; }
        public string user_Note { get; set; }
        public Nullable<System.DateTime> user_Createtime { get; set; }
        public Nullable<System.DateTime> user_Updatetime { get; set; }
        public Nullable<int> user_IsAudit { get; set; }
        public string user_AuditStatus { get; set; }
        public Nullable<int> user_Order { get; set; }
        public string user_Tel { get; set; }
    }
}
