//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ConstructionProject_Dept
    {
        public string Dept_Id { get; set; }
        public int ID { get; set; }
        public string xmys { get; set; }
        public string zjly { get; set; }
        public string xmfzr { get; set; }
        public string fzrdwdh { get; set; }
        public Nullable<int> fzrsj { get; set; }
        public string xmlxr { get; set; }
        public string lxrdwdh { get; set; }
        public Nullable<int> lxrsj { get; set; }
        public System.DateTime OperatTime { get; set; }
        public int OperatPid { get; set; }
        public string Dept_Name { get; set; }
        public string Dept_Code { get; set; }
        public string Dept_FatherId { get; set; }
        public Nullable<int> Dept_Order { get; set; }
    }
}
