//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Equipment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Network_Dept
    {
        public int ID { get; set; }
        public string Dept_Id { get; set; }
        public Nullable<int> scjhj { get; set; }
        public string scjhjxh { get; set; }
        public string scjhjpp { get; set; }
        public Nullable<int> ecjhj { get; set; }
        public string ecjhjxh { get; set; }
        public string ecjhjpp { get; set; }
        public Nullable<int> lyq { get; set; }
        public string lyqxh { get; set; }
        public string lyqpp { get; set; }
        public Nullable<int> gdj { get; set; }
        public string gdjxh { get; set; }
        public string gdjpp { get; set; }
        public Nullable<int> llfzjh { get; set; }
        public string llfzjhxh { get; set; }
        public string llfzjhpp { get; set; }
        public Nullable<int> gx { get; set; }
        public Nullable<int> wxjrd { get; set; }
        public Nullable<int> wxzj { get; set; }
        public string wxzjxh { get; set; }
        public string wxzjpp { get; set; }
        public string flwck { get; set; }
        public string jrcwwwIpdzd { get; set; }
        public System.DateTime OperatTime { get; set; }
        public int OperatPid { get; set; }
        public string Dept_Name { get; set; }
        public string Dept_Code { get; set; }
        public string Dept_FatherId { get; set; }
        public Nullable<int> Dept_Order { get; set; }
    }
}
